In [12]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv("google_analitycs_log.csv", delimiter=',')
df[:10]

          day act_1_day         cash
0  01.09.2017     2 488  18 253,10 $
1  02.09.2017     1 917   4 519,44 $
2  03.09.2017     2 050   5 491,20 $
3  04.09.2017     2 295   7 966,64 $
4  05.09.2017     2 824  11 204,61 $
5  06.09.2017     2 797  13 892,14 $
6  07.09.2017     2 747  15 598,08 $
7  08.09.2017     2 509   5 747,30 $
8  09.09.2017     1 986   8 289,30 $
9  10.09.2017     1 968   7 307,95 $

In [14]:
mean = df['act_1_day']#.aggregate(np.mean)
for val in mean:
    if not isinstance(val, float):
        print('Error: val = {!r}'.format(val))

Error: val = '2\xa0488'
Error: val = '1\xa0917'
Error: val = '2\xa0050'
Error: val = '2\xa0295'
Error: val = '2\xa0824'
Error: val = '2\xa0797'
Error: val = '2\xa0747'
Error: val = '2\xa0509'
Error: val = '1\xa0986'
Error: val = '1\xa0968'
Error: val = '2\xa0836'
Error: val = '2\xa0813'
Error: val = '2\xa0774'
Error: val = '2\xa0790'
Error: val = '2\xa0553'
Error: val = '2\xa0590'
Error: val = '2\xa0682'
Error: val = '3\xa0477'
Error: val = '3\xa0313'
Error: val = '4\xa0825'
Error: val = '4\xa0751'
Error: val = '3\xa0592'
Error: val = '2\xa0174'
Error: val = '2\xa0483'
Error: val = '3\xa0115'
Error: val = '3\xa0701'
Error: val = '3\xa0338'
Error: val = '3\xa0371'
Error: val = '2\xa0974'
Error: val = '2\xa0491'
Error: val = '2\xa0756'
Error: val = '3\xa0393'
Error: val = '3\xa0448'
Error: val = '5\xa0049'
Error: val = '4\xa0603'
Error: val = '3\xa0886'
Error: val = '3\xa0248'
Error: val = '3\xa0166'
Error: val = '3\xa0900'
Error: val = '3\xa0843'
Error: val = '3\xa0313'
Error: val = '3\xa0067'
Error: val = '2\xa0695'
Error: val = '2\xa0365'
Error: val = '2\xa0091'
Error: val = '3\xa0044'
Error: val = '4\xa0115'
Error: val = '3\xa0474'
Error: val = '3\xa0194'
Error: val = '2\xa0958'
Error: val = '2\xa0235'
Error: val = '2\xa0653'
Error: val = '3\xa0481'
Error: val = '3\xa0331'
Error: val = '3\xa0360'
Error: val = '3\xa0453'
Error: val = '3\xa0048'
Error: val = '2\xa0268'
Error: val = '2\xa0231'
Error: val = '3\xa0123'
Error: val = '2\xa0771'
Error: val = '2\xa0995'
Error: val = '2\xa0975'
Error: val = '2\xa0913'
Error: val = '2\xa0205'
Error: val = '2\xa0507'
Error: val = '3\xa0469'
Error: val = '3\xa0684'
Error: val = '3\xa0992'
Error: val = '3\xa0428'
Error: val = '3\xa0060'
Error: val = '2\xa0355'
Error: val = '2\xa0584'
Error: val = '3\xa0273'
Error: val = '3\xa0407'
Error: val = '3\xa0393'
Error: val = '3\xa0350'
Error: val = '3\xa0106'
Error: val = '2\xa0078'
Error: val = '2\xa0245'
Error: val = '3\xa0247'
Error: val = '2\xa0873'
Error: val = '3\xa0061'
Error: val = '2\xa0971'
Error: val = '2\xa0991'
Error: val = '2\xa0244'
Error: val = '2\xa0523'
Error: val = '4\xa0446'
Error: val = '3\xa0706'
Error: val = '3\xa0407'
Error: val = '3\xa0076'
Error: val = '2\xa0877'
Error: val = '2\xa0171'
Error: val = '2\xa0361'
Error: val = '3\xa0251'
Error: val = '3\xa0399'
Error: val = '3\xa0502'
Error: val = '3\xa0435'
Error: val = '2\xa0860'
Error: val = '2\xa0193'
Error: val = '2\xa0487'
Error: val = '3\xa0308'
Error: val = '9\xa0085'
Error: val = '8\xa0760'
Error: val = '3\xa0505'
Error: val = '3\xa0400'
Error: val = '2\xa0530'
Error: val = '2\xa0509'
Error: val = '3\xa0733'
Error: val = '3\xa0449'
Error: val = '3\xa0208'
Error: val = '2\xa0973'
Error: val = '2\xa0481'
Error: val = '1\xa0977'
Error: val = '1\xa0900'
Error: val = '2\xa0063'
Error: val = '2\xa0369'
Error: val = '2\xa0744'
Error: val = '2\xa0291'
Error: val = '1\xa0909'
Error: val = '1\xa0728'
Error: val = '1\xa0489'
Error: val = '1\xa0800'
Error: val = '2\xa0874'
Error: val = '2\xa0742'
Error: val = '2\xa0747'
Error: val = '2\xa0535'
Error: val = '1\xa0865'
Error: val = '2\xa0020'
Error: val = '2\xa0735'
Error: val = '3\xa0104'
Error: val = '3\xa0057'
Error: val = '2\xa0812'
Error: val = '2\xa0668'
Error: val = '2\xa0058'
Error: val = '2\xa0122'
Error: val = '2\xa0946'
Error: val = '3\xa0133'
Error: val = '2\xa0983'
Error: val = '2\xa0717'
Error: val = '2\xa0664'
Error: val = '1\xa0948'
Error: val = '1\xa0996'
Error: val = '2\xa0870'
Error: val = '2\xa0806'
Error: val = '2\xa0791'
Error: val = '3\xa0232'
Error: val = '2\xa0565'
Error: val = '2\xa0002'
Error: val = '2\xa0141'
Error: val = '2\xa0923'
Error: val = '2\xa0946'
Error: val = '2\xa0840'
Error: val = '2\xa0893'
Error: val = '2\xa0552'
Error: val = '1\xa0970'
Error: val = '2\xa0090'
Error: val = '2\xa0913'
Error: val = '2\xa0865'
Error: val = '2\xa0876'
Error: val = '2\xa0790'
Error: val = '2\xa0778'
Error: val = '2\xa0387'
Error: val = '2\xa0607'
Error: val = '3\xa0395'
Error: val = '3\xa0293'
Error: val = '3\xa0075'
Error: val = '2\xa0923'
Error: val = '2\xa0620'
Error: val = '2\xa0267'
Error: val = '2\xa0471'
Error: val = '2\xa0755'
Error: val = '3\xa0395'
Error: val = '3\xa0244'
Error: val = '3\xa0422'
Error: val = '2\xa0901'
Error: val = '2\xa0143'
Error: val = '2\xa0326'
Error: val = '3\xa0846'
Error: val = '3\xa0302'
Error: val = '3\xa0008'
Error: val = '2\xa0961'
Error: val = '2\xa0768'
Error: val = '2\xa0242'
Error: val = '2\xa0286'
Error: val = '3\xa0092'
Error: val = '3\xa0591'
Error: val = '3\xa0011'
Error: val = '2\xa0918'
Error: val = '2\xa0735'
Error: val = '2\xa0154'
Error: val = '2\xa0119'
Error: val = '3\xa0403'
Error: val = '3\xa0278'
Error: val = '3\xa0216'
Error: val = '3\xa0624'
Error: val = '3\xa0042'
Error: val = '2\xa0174'
Error: val = '2\xa0244'
Error: val = '3\xa0520'
Error: val = '3\xa0171'
Error: val = '4\xa0349'
Error: val = '3\xa0555'
Error: val = '2\xa0968'
Error: val = '2\xa0202'
Error: val = '2\xa0157'
Error: val = '3\xa0223'
Error: val = '4\xa0231'
Error: val = '3\xa0731'
Error: val = '3\xa0473'
Error: val = '2\xa0728'
Error: val = '1\xa0868'
Error: val = '2\xa0094'

In [15]:
'2 488'.replace(' ','')

'2488'

In [16]:
active = []
for item in df['act_1_day']:
    active.append(float(item.replace(u'\xa0','')))
for index, row in df.iterrows():
        df.set_value(index, 'normal', float(row['cash'].replace('\xa0', '').replace('$', '').replace(',', '.')))
mean = np.mean(active)
mean

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:5: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  """

2944.478873239437

In [19]:
def get_anomalies_by_users_a_day(df, mean, fluct=0.25, col='normal'):
    if not isinstance(fluct, float) or fluct < 0 or fluct > 1:
        print("Give fluctuation in range of [0-1]")
        return
    for index, row in df.iterrows():
        #value = float(row[col].replace(u'\xa0',''))
        value = row[col]
        if value > mean*(1 + fluct) or value < mean*(1 - fluct):
            print("Day of anomaly: {}".format(row['day']))

In [20]:
get_anomalies_by_users_a_day(df, mean, 0.4)

Day of anomaly: 01.09.2017
Day of anomaly: 02.09.2017
Day of anomaly: 03.09.2017
Day of anomaly: 04.09.2017
Day of anomaly: 05.09.2017
Day of anomaly: 06.09.2017
Day of anomaly: 07.09.2017
Day of anomaly: 08.09.2017
Day of anomaly: 09.09.2017
Day of anomaly: 10.09.2017
Day of anomaly: 11.09.2017
Day of anomaly: 12.09.2017
Day of anomaly: 13.09.2017
Day of anomaly: 14.09.2017
Day of anomaly: 15.09.2017
Day of anomaly: 16.09.2017
Day of anomaly: 17.09.2017
Day of anomaly: 18.09.2017
Day of anomaly: 19.09.2017
Day of anomaly: 20.09.2017
Day of anomaly: 21.09.2017
Day of anomaly: 22.09.2017
Day of anomaly: 23.09.2017
Day of anomaly: 24.09.2017
Day of anomaly: 25.09.2017
Day of anomaly: 26.09.2017
Day of anomaly: 27.09.2017
Day of anomaly: 28.09.2017
Day of anomaly: 29.09.2017
Day of anomaly: 30.09.2017
Day of anomaly: 01.10.2017
Day of anomaly: 02.10.2017
Day of anomaly: 03.10.2017
Day of anomaly: 04.10.2017
Day of anomaly: 05.10.2017
Day of anomaly: 06.10.2017
Day of anomaly: 07.10.2017
Day of anomaly: 08.10.2017
Day of anomaly: 09.10.2017
Day of anomaly: 10.10.2017
Day of anomaly: 11.10.2017
Day of anomaly: 12.10.2017
Day of anomaly: 13.10.2017
Day of anomaly: 14.10.2017
Day of anomaly: 15.10.2017
Day of anomaly: 16.10.2017
Day of anomaly: 17.10.2017
Day of anomaly: 18.10.2017
Day of anomaly: 19.10.2017
Day of anomaly: 20.10.2017
Day of anomaly: 21.10.2017
Day of anomaly: 22.10.2017
Day of anomaly: 23.10.2017
Day of anomaly: 24.10.2017
Day of anomaly: 25.10.2017
Day of anomaly: 26.10.2017
Day of anomaly: 27.10.2017
Day of anomaly: 28.10.2017
Day of anomaly: 29.10.2017
Day of anomaly: 30.10.2017
Day of anomaly: 31.10.2017
Day of anomaly: 01.11.2017
Day of anomaly: 02.11.2017
Day of anomaly: 03.11.2017
Day of anomaly: 04.11.2017
Day of anomaly: 05.11.2017
Day of anomaly: 06.11.2017
Day of anomaly: 07.11.2017
Day of anomaly: 08.11.2017
Day of anomaly: 09.11.2017
Day of anomaly: 10.11.2017
Day of anomaly: 11.11.2017
Day of anomaly: 12.11.2017
Day of anomaly: 13.11.2017
Day of anomaly: 14.11.2017
Day of anomaly: 15.11.2017
Day of anomaly: 16.11.2017
Day of anomaly: 17.11.2017
Day of anomaly: 18.11.2017
Day of anomaly: 19.11.2017
Day of anomaly: 20.11.2017
Day of anomaly: 21.11.2017
Day of anomaly: 22.11.2017
Day of anomaly: 23.11.2017
Day of anomaly: 24.11.2017
Day of anomaly: 25.11.2017
Day of anomaly: 26.11.2017
Day of anomaly: 27.11.2017
Day of anomaly: 28.11.2017
Day of anomaly: 29.11.2017
Day of anomaly: 30.11.2017
Day of anomaly: 01.12.2017
Day of anomaly: 02.12.2017
Day of anomaly: 03.12.2017
Day of anomaly: 04.12.2017
Day of anomaly: 05.12.2017
Day of anomaly: 06.12.2017
Day of anomaly: 07.12.2017
Day of anomaly: 08.12.2017
Day of anomaly: 09.12.2017
Day of anomaly: 10.12.2017
Day of anomaly: 11.12.2017
Day of anomaly: 12.12.2017
Day of anomaly: 13.12.2017
Day of anomaly: 14.12.2017
Day of anomaly: 15.12.2017
Day of anomaly: 16.12.2017
Day of anomaly: 17.12.2017
Day of anomaly: 18.12.2017
Day of anomaly: 19.12.2017
Day of anomaly: 20.12.2017
Day of anomaly: 21.12.2017
Day of anomaly: 22.12.2017
Day of anomaly: 23.12.2017
Day of anomaly: 24.12.2017
Day of anomaly: 25.12.2017
Day of anomaly: 26.12.2017
Day of anomaly: 27.12.2017
Day of anomaly: 28.12.2017
Day of anomaly: 29.12.2017
Day of anomaly: 30.12.2017
Day of anomaly: 31.12.2017
Day of anomaly: 01.01.2018
Day of anomaly: 02.01.2018
Day of anomaly: 03.01.2018
Day of anomaly: 04.01.2018
Day of anomaly: 05.01.2018
Day of anomaly: 06.01.2018
Day of anomaly: 07.01.2018
Day of anomaly: 08.01.2018
Day of anomaly: 09.01.2018
Day of anomaly: 10.01.2018
Day of anomaly: 11.01.2018
Day of anomaly: 12.01.2018
Day of anomaly: 13.01.2018
Day of anomaly: 14.01.2018
Day of anomaly: 15.01.2018
Day of anomaly: 16.01.2018
Day of anomaly: 17.01.2018
Day of anomaly: 18.01.2018
Day of anomaly: 19.01.2018
Day of anomaly: 20.01.2018
Day of anomaly: 21.01.2018
Day of anomaly: 22.01.2018
Day of anomaly: 23.01.2018
Day of anomaly: 24.01.2018
Day of anomaly: 25.01.2018
Day of anomaly: 26.01.2018
Day of anomaly: 27.01.2018
Day of anomaly: 28.01.2018
Day of anomaly: 29.01.2018
Day of anomaly: 30.01.2018
Day of anomaly: 31.01.2018
Day of anomaly: 01.02.2018
Day of anomaly: 02.02.2018
Day of anomaly: 03.02.2018
Day of anomaly: 04.02.2018
Day of anomaly: 05.02.2018
Day of anomaly: 06.02.2018
Day of anomaly: 07.02.2018
Day of anomaly: 08.02.2018
Day of anomaly: 09.02.2018
Day of anomaly: 10.02.2018
Day of anomaly: 11.02.2018
Day of anomaly: 12.02.2018
Day of anomaly: 13.02.2018
Day of anomaly: 14.02.2018
Day of anomaly: 15.02.2018
Day of anomaly: 16.02.2018
Day of anomaly: 17.02.2018
Day of anomaly: 18.02.2018
Day of anomaly: 19.02.2018
Day of anomaly: 20.02.2018
Day of anomaly: 21.02.2018
Day of anomaly: 22.02.2018
Day of anomaly: 23.02.2018
Day of anomaly: 24.02.2018
Day of anomaly: 25.02.2018
Day of anomaly: 26.02.2018
Day of anomaly: 27.02.2018
Day of anomaly: 28.02.2018
Day of anomaly: 01.03.2018
Day of anomaly: 02.03.2018
Day of anomaly: 03.03.2018
Day of anomaly: 04.03.2018
Day of anomaly: 05.03.2018
Day of anomaly: 06.03.2018
Day of anomaly: 07.03.2018
Day of anomaly: 08.03.2018
Day of anomaly: 09.03.2018
Day of anomaly: 10.03.2018
Day of anomaly: 11.03.2018
Day of anomaly: 12.03.2018
Day of anomaly: 13.03.2018
Day of anomaly: 14.03.2018
Day of anomaly: 15.03.2018
Day of anomaly: 16.03.2018
Day of anomaly: 17.03.2018
Day of anomaly: 18.03.2018
Day of anomaly: 19.03.2018
Day of anomaly: 20.03.2018
Day of anomaly: 21.03.2018
Day of anomaly: 22.03.2018
Day of anomaly: 23.03.2018
Day of anomaly: 24.03.2018
Day of anomaly: 25.03.2018
Day of anomaly: 26.03.2018
Day of anomaly: 27.03.2018
Day of anomaly: 28.03.2018
Day of anomaly: 29.03.2018
Day of anomaly: 30.03.2018
Day of anomaly: 31.03.2018
Day of anomaly: 01.04.2018

In [21]:
df = pd.read_csv("google_analitycs_log_cash.csv", delimiter=',')
df[:10]

          day act_1_day         cash
0  01.09.2017     2 488  18 253,10 $
1  02.09.2017     1 917   4 519,44 $
2  03.09.2017     2 050   5 491,20 $
3  04.09.2017     2 295   7 966,64 $
4  05.09.2017     2 824  11 204,61 $
5  06.09.2017     2 797  13 892,14 $
6  07.09.2017     2 747  15 598,08 $
7  08.09.2017     2 509   5 747,30 $
8  09.09.2017     1 986   8 289,30 $
9  10.09.2017     1 968   7 307,95 $

In [22]:
for index, row in df.iterrows():
        df.set_value(index, 'normal', float(row['cash'].replace('\xa0', '').replace('$', '').replace(',', '.')))
df[:10]

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

          day act_1_day         cash    normal
0  01.09.2017     2 488  18 253,10 $  18253.10
1  02.09.2017     1 917   4 519,44 $   4519.44
2  03.09.2017     2 050   5 491,20 $   5491.20
3  04.09.2017     2 295   7 966,64 $   7966.64
4  05.09.2017     2 824  11 204,61 $  11204.61
5  06.09.2017     2 797  13 892,14 $  13892.14
6  07.09.2017     2 747  15 598,08 $  15598.08
7  08.09.2017     2 509   5 747,30 $   5747.30
8  09.09.2017     1 986   8 289,30 $   8289.30
9  10.09.2017     1 968   7 307,95 $   7307.95

In [23]:
mean = df['normal'].aggregate(np.mean)
mean

15321.803708920186

In [24]:
get_anomalies_by_users_a_day(df, mean, 0.4, 'normal')

Day of anomaly: 02.09.2017
Day of anomaly: 03.09.2017
Day of anomaly: 04.09.2017
Day of anomaly: 08.09.2017
Day of anomaly: 09.09.2017
Day of anomaly: 10.09.2017
Day of anomaly: 13.09.2017
Day of anomaly: 16.09.2017
Day of anomaly: 17.09.2017
Day of anomaly: 22.09.2017
Day of anomaly: 27.09.2017
Day of anomaly: 07.10.2017
Day of anomaly: 12.10.2017
Day of anomaly: 14.10.2017
Day of anomaly: 04.11.2017
Day of anomaly: 13.11.2017
Day of anomaly: 14.11.2017
Day of anomaly: 22.11.2017
Day of anomaly: 24.11.2017
Day of anomaly: 27.11.2017
Day of anomaly: 28.11.2017
Day of anomaly: 29.11.2017
Day of anomaly: 04.12.2017
Day of anomaly: 05.12.2017
Day of anomaly: 06.12.2017
Day of anomaly: 08.12.2017
Day of anomaly: 11.12.2017
Day of anomaly: 13.12.2017
Day of anomaly: 14.12.2017
Day of anomaly: 15.12.2017
Day of anomaly: 18.12.2017
Day of anomaly: 19.12.2017
Day of anomaly: 20.12.2017
Day of anomaly: 23.12.2017
Day of anomaly: 24.12.2017
Day of anomaly: 30.12.2017
Day of anomaly: 02.01.2018
Day of anomaly: 07.01.2018
Day of anomaly: 13.01.2018
Day of anomaly: 20.01.2018
Day of anomaly: 28.01.2018
Day of anomaly: 03.02.2018
Day of anomaly: 10.02.2018
Day of anomaly: 11.02.2018
Day of anomaly: 15.02.2018
Day of anomaly: 17.02.2018
Day of anomaly: 18.02.2018
Day of anomaly: 24.02.2018
Day of anomaly: 25.02.2018
Day of anomaly: 03.03.2018
Day of anomaly: 10.03.2018
Day of anomaly: 11.03.2018
Day of anomaly: 14.03.2018
Day of anomaly: 15.03.2018
Day of anomaly: 19.03.2018
Day of anomaly: 26.03.2018
Day of anomaly: 27.03.2018
Day of anomaly: 28.03.2018
Day of anomaly: 29.03.2018
Day of anomaly: 30.03.2018